name: test_workflow

on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
    - name: Print Greeting
      run: echo "Hello from my Rust Project!" 
    - name: Print Explain
      run: echo "Playing with GitHub Action Workflows!" 
